-- BuzzRecs — Date Night SEED (Chicago recognized restaurants & bars).
-- Run AFTER 2026-07-20-date-nights.sql, via the dashboard SQL editor.
-- Idempotent + safe: new venues insert into `places` only if a place of the
-- same name doesn't already exist (existing venues like Gilt Bar / Gus' Sip &
-- Dip are matched by name, never duplicated); each date_nights row attaches by
-- name. Re-running changes nothing.
-- Sources: MICHELIN Guide Chicago 2025 (stars + Bib Gourmand), NYT Best of
-- Chicago, North America's 50 Best Bars 2026.

create temporary table dn_seed (
  name text, slug text, neighborhood text, address text, website_url text,
  reservation_url text, description text, michelin_stars int, bib_gourmand boolean,
  fifty_best text, nyt boolean, cuisine text, price text, reservation_platform text
) on commit drop;

insert into dn_seed (name, slug, neighborhood, address, website_url, reservation_url, description, michelin_stars, bib_gourmand, fifty_best, nyt, cuisine, price, reservation_platform) values
  ('Smyth', 'smyth', 'West Loop', '177 N Ada St Suite 101, Chicago, IL 60607', 'https://www.smythandtheloyalist.com', 'https://www.exploretock.com/smyth', 'Chicago''s lone three-star, where John and Karen Urie Shields turn garden-grown produce into boundary-pushing art in a chic, candlelit room built for a once-a-year splurge.', 3, false, null, false, 'Contemporary tasting menu', '$$$$', 'Tock'),
  ('Alinea', 'alinea', 'Lincoln Park', '1723 N Halsted St, Chicago, IL 60614', 'https://www.alinearestaurant.com', 'https://www.exploretock.com/alinea', 'Grant Achatz''s two-star theater of edible balloons and tableside dessert-painting remains the city''s most immersive splurge and a bucket-list night out.', 2, false, null, false, 'Modernist tasting menu', '$$$$', 'Tock'),
  ('Ever', 'ever', 'Fulton Market', '1340 W Fulton St, Chicago, IL 60607', 'https://www.ever-restaurant.com', 'https://www.exploretock.com/ever', 'Curtis Duffy''s two-star jewel box glows with starry lighting and flawless service, and its adjoining cocktail bar makes it a full-evening date destination the NYT loves too.', 2, false, null, true, 'Modern American tasting menu', '$$$$', 'Tock'),
  ('Kasama', 'kasama', 'Ukrainian Village', '1001 N Winchester Ave, Chicago, IL 60622', 'https://www.kasamachicago.com', 'https://resy.com/cities/chicago-il/venues/kasama', 'Genie Kwon and Tim Flores''s beloved bakery-by-day earned a second star in 2025 for its singular Filipino-American tasting menu — the hottest reservation in town.', 2, false, null, true, 'Filipino', '$$$', 'Resy'),
  ('Oriole', 'oriole', 'West Loop', '661 W Walnut St, Chicago, IL 60661', 'https://www.oriolechicago.com', 'https://www.exploretock.com/oriole', 'Entered through a freight elevator and hidden down a loading dock, Noah Sandoval''s two-star tasting blends French and Japanese finesse for a discreetly romantic occasion.', 2, false, null, true, 'Contemporary tasting menu', '$$$$', 'Tock'),
  ('Boka', 'boka', 'Lincoln Park', '1729 N Halsted St, Chicago, IL 60614', 'https://www.bokachicago.com', 'https://www.opentable.com/boka', 'A decade-plus of Michelin stars hasn''t dimmed Lee Wolen''s elegant, banquette-lined flagship, a perennial pre-theater date-night classic and NYT favorite.', 1, false, null, true, 'New American', '$$$$', 'OpenTable'),
  ('Carino', 'carino', 'Uptown', '4662 N Broadway Ave, Chicago, IL 60640', 'https://www.carinochicago.com', null, 'Under the rumbling Uptown ''L,'' Norman Fenton''s energetic counter-seat tasting mines Mexican tradition with huitlacoche ravioli and al pastor-style lamb — intimate and star-worthy.', 1, false, null, false, 'Modern Mexican tasting menu', '$$$$', 'Tock'),
  ('EL Ideas', 'el-ideas', 'Douglas Park', '2419 W 14th St, Chicago, IL 60608', 'https://www.elideas.com', null, 'Phillip Foss cooks in his literal home for one BYOB seating a night, where you can wander the kitchen — a playful, one-of-a-kind starred experience for adventurous couples.', 1, false, null, false, 'Contemporary American tasting menu', '$$$$', 'Tock'),
  ('Elske', 'elske', 'West Loop', '1350 W Randolph St, Chicago, IL 60607', 'https://www.elskerestaurant.com', null, 'David and Anna Posey''s Danish-hearted charmer flows from a fire-pit patio into an airy room, offering both tasting and a la carte for a warmly stylish starred night.', 1, false, null, false, 'Contemporary (Danish-inflected)', '$$$$', 'Tock'),
  ('Esme', 'esme', 'Lincoln Park', '2200 N Clark St, Chicago, IL 60614', 'https://www.esmechicago.com', null, 'Jenner Tomaska''s gallery-like atelier plates each course on artist-made ceramics, blurring art and dining into a high-concept, star-lit evening.', 1, false, null, false, 'Contemporary American tasting menu', '$$$$', 'Tock'),
  ('Feld', 'feld', 'Ukrainian Village', '2018 W Chicago Ave, Chicago, IL 60622', 'https://www.feldrestaurant.com', null, 'New for 2025 with a star and a Green Star, Jacob Potashnick''s theater-in-the-round kitchen sources within four hours of the city — book the fire-pit backyard when it''s warm.', 1, false, null, false, 'Contemporary farm-to-table tasting menu', '$$$$', 'Tock'),
  ('Galit', 'galit', 'Lincoln Park', '2429 N Lincoln Ave, Chicago, IL 60614', 'https://www.galitrestaurant.com', 'https://resy.com/cities/chicago-il/venues/galit', 'Zach Engel''s lively, aromatic room turns flame-kissed pita, creamy hummus and esoteric regional wines into one of the country''s best neo-Israeli tables — and a warm starred value.', 1, false, null, false, 'Middle Eastern', '$$', 'Resy'),
  ('Indienne', 'indienne', 'River North', '217 W Huron St, Chicago, IL 60654', 'https://www.indiennechicago.com', null, 'Sujan Sarkar''s refined, French-touched Indian tasting arrives like art but tastes like home, set in a plush room of rose-pink booths and white linen.', 1, false, null, false, 'Modern Indian tasting menu', '$$$$', 'Tock'),
  ('Mako', 'mako', 'West Loop', '731 W Lake St, Chicago, IL 60661', 'https://www.makochicago.com', null, 'B.K. Park''s near-hidden 22-seat shrine to omakase is pure focus and finesse — an intimate sushi date for two who love the counter.', 1, false, null, false, 'Japanese omakase', '$$$$', 'Tock'),
  ('Moody Tongue', 'moody-tongue', 'South Loop', '2515 S Wabash Ave, Chicago, IL 60616', 'https://www.moodytongue.com', null, 'Perched atop a working brewery, this moody, masculine room pairs an inventive tasting menu with virtuosic house-brewed beers — a distinctive starred date for beer lovers.', 1, false, null, false, 'Contemporary tasting menu (beer pairing)', '$$$$', 'Tock'),
  ('Next', 'next', 'Fulton Market', '953 W Fulton Market, Chicago, IL 60607', 'https://www.nextrestaurant.com', 'https://www.exploretock.com/next', 'Grant Achatz''s shape-shifting concept reinvents itself each season — Paris 1906 one menu, ancient Rome the next — making every visit pure dinner theater.', 1, false, null, false, 'Contemporary themed tasting menu', '$$$$', 'Tock'),
  ('Schwa', 'schwa', 'Wicker Park', '1466 N Ashland Ave, Chicago, IL 60622', 'https://www.schwarestaurant.com', null, 'No servers, rap booming overhead, and wildly imaginative BYOB cooking — Schwa''s punk spirit makes for a memorably offbeat starred night, if you can get through.', 1, false, null, false, 'Contemporary American tasting menu', '$$$', 'Tock'),
  ('Sepia', 'sepia', 'West Loop', '123 N Jefferson St, Chicago, IL 60661', 'https://www.sepiachicago.com', null, 'Set in a 19th-century print shop with exposed brick and dramatic chandeliers, Andrew Zimmerman''s globally-accented American cooking is a polished, romantic classic.', 1, false, null, false, 'New American', '$$$$', 'Tock'),
  ('Topolobampo', 'topolobampo', 'River North', '445 N Clark St, Chicago, IL 60654', 'https://www.rickbayless.com/restaurants/topolobampo', null, 'The jewel in Rick Bayless''s crown spins seasonal, tradition-rooted Mexican fine dining with an agave-spirit pairing that''s an education unto itself.', 1, false, null, false, 'Fine Mexican', '$$$$', 'Tock'),
  ('Birrieria Zaragoza', 'birrieria-zaragoza', 'Archer Heights', '4852 S Pulaski Rd, Chicago, IL 60632', 'https://www.birrieriazaragoza.com', null, 'A family-run Southwest Side temple to slow-roasted goat birria, its consome and hand-pressed tortillas long adored by inspectors as a Bib Gourmand gem.', 0, true, null, false, 'Mexican (goat birria)', '$', 'Walk-in'),
  ('Boonie''s', 'boonies', 'North Center', '4337 N Western Ave, Chicago, IL 60618', 'https://www.booniefoods.com', 'https://resy.com/cities/chicago-il/venues/boonies-filipino-restaurant', 'Born from a pop-up, this modern Filipino-American Bib charms with grilled liempo skewers and an ube semifreddo sandwich — start with the ube colada.', 0, true, null, false, 'Filipino', '$$', 'Resy'),
  ('Cellar Door Provisions', 'cellar-door-provisions', 'Logan Square', '3025 W Diversey Ave, Chicago, IL 60647', 'https://www.cellardoorprovisions.com', 'https://resy.com/cities/chicago-il/venues/cellar-door-provisions', 'Ethan Pikas''s cult bakery-turned-restaurant plates ethereal breads by day and hearty, artful Midwestern dinners by night — a quietly special Bib Gourmand.', 0, true, null, false, 'New American bakery-restaurant', '$$', 'Resy'),
  ('Chef''s Special Cocktail Bar', 'chefs-special-cocktail-bar', 'Bucktown', '2165 N Western Ave, Chicago, IL 60647', null, 'https://resy.com/cities/chicago-il/venues/chefs-special-cocktail-bar', 'From the Giant team, this Midwest-tavern-meets-Chinatown Bib pours finessed tropical cocktails alongside can''t-miss walnut shrimp — a fun, low-key date.', 0, true, null, false, 'American-Chinese & cocktails', '$', 'Resy'),
  ('Chilam Balam', 'chilam-balam', 'Lakeview', '3023 N Broadway, Chicago, IL 60657', 'https://www.chilambalamchicago.com', null, 'A snug, sustainable, BYOB basement spot turning seasonal produce into inventive small-plate Mexican — a longtime Bib Gourmand sweetheart.', 0, true, null, false, 'Modern Mexican', '$$', 'OpenTable'),
  ('Ciccio Mio', 'ciccio-mio', 'River North', '226 W Kinzie St, Chicago, IL 60654', 'https://www.cicciomio.com', 'https://resy.com/cities/chicago-il/venues/ciccio-mio', 'Nostalgic, fancified red-sauce Italian and food-loving wines make this luxe River North Bib a genuinely cozy date-night pick.', 0, true, null, false, 'Italian', '$$$', 'Resy'),
  ('Daisies', 'daisies', 'Logan Square', '2523 N Milwaukee Ave, Chicago, IL 60647', 'https://www.daisieschicago.com', null, 'A vegetable-forward pasta haven that holds both a Bib Gourmand and a Michelin Green Star for its farm-driven, sustainable Logan Square cooking.', 0, true, null, false, 'Italian (pasta)', '$$', 'OpenTable'),
  ('Frontera Grill', 'frontera-grill', 'River North', '445 N Clark St, Chicago, IL 60654', 'https://www.rickbayless.com/restaurants/frontera-grill', 'https://resy.com/cities/chicago-il/venues/frontera-grill', 'Rick Bayless''s icon is an icon for good reason — come hungry, order for the table, and taste why it''s an enduring Bib Gourmand institution.', 0, true, null, false, 'Mexican', '$$$', 'Resy'),
  ('Ghin Khao', 'ghin-khao', 'Pilsen', '2128 W Cermak Rd, Chicago, IL 60608', 'https://www.ghinkhaochicago.com', null, 'A fast-casual Pilsen counter proving ''eat rice'' is a love language, its punchy, home-style Thai cooking a Bib Gourmand steal.', 0, true, null, false, 'Thai', '$', 'Walk-in'),
  ('Giant', 'giant', 'Logan Square', '3209 W Armitage Ave, Chicago, IL 60647', 'https://www.giantrestaurant.com', 'https://resy.com/cities/chicago-il/venues/giant', 'Jason Vincent''s snug, ever-evolving neighborhood darling serves dynamic seasonal American plates and house pasta — a hard-to-book Bib worth the effort.', 0, true, null, false, 'New American', '$$', 'Resy'),
  ('Gilt Bar', 'gilt-bar', 'River North', '230 W Kinzie St, Chicago, IL 60654', 'https://www.giltbarchicago.com', 'https://resy.com/cities/chicago-il/venues/gilt-bar', 'A dim, candlelit temple to drinking in restaurants and eating in bars, this gastropub Bib is made for a moody, unhurried date.', 0, true, null, false, 'American gastropub', '$$', 'Resy'),
  ('Girl & The Goat', 'girl-and-the-goat', 'West Loop', '809 W Randolph St, Chicago, IL 60607', 'https://www.girlandthegoat.com', null, 'Stephanie Izard''s buzzing, wood-fired Randolph Row flagship is still one of the city''s most fun tables — a boisterous, shareable Bib Gourmand night out.', 0, true, null, false, 'New American (live-fire small plates)', '$$$', 'OpenTable'),
  ('HaiSous', 'haisous', 'Pilsen', '1800 S Carpenter St, Chicago, IL 60608', 'https://www.haisous.com', null, 'Thai and Danielle Dang''s elegant Pilsen Vietnamese restaurant grills, sizzles and pours (don''t skip the Ca Phe Bar) for a stylish, soulful Bib date.', 0, true, null, false, 'Vietnamese', '$$', 'OpenTable'),
  ('Kie-Gol-Lanee', 'kie-gol-lanee', 'Uptown', '5004 N Sheridan Rd, Chicago, IL 60640', null, null, 'An Uptown ode to Oaxaca where house-made moles and mezcal deliver deep, regional flavor at a Bib Gourmand''s gentle price.', 0, true, null, false, 'Oaxacan Mexican', '$$', 'OpenTable'),
  ('Lardon', 'lardon', 'Logan Square', '2200 N California Ave Suite 102, Chicago, IL 60647', 'https://www.lardonchicago.com', 'https://resy.com/cities/chicago-il/venues/lardon', 'A charcuterie-obsessed salumeria plating house sausages, pates and artisan cheeses across four cuisines — a snug, feel-at-home Bib Gourmand.', 0, true, null, false, 'Charcuterie & salumi', '$', 'Resy'),
  ('Longman & Eagle', 'longman-and-eagle', 'Logan Square', '2657 N Kedzie Ave, Chicago, IL 60647', 'https://www.longmanandeagle.com', 'https://resy.com/cities/chicago-il/venues/longman-and-eagle', 'A whiskey-soaked, nose-to-tail Logan Square institution with a rooming house upstairs — its ever-changing regional American menu is a longtime Bib favorite.', 0, true, null, false, 'New American', '$$', 'Resy'),
  ('Lula Cafe', 'lula-cafe', 'Logan Square', '2537 N Kedzie Blvd, Chicago, IL 60647', 'https://www.lulacafe.com', 'https://resy.com/cities/chicago-il/venues/lula-cafe', 'Farm-to-table since 1999, this beloved Logan Square all-day cafe is both a Bib Gourmand and an NYT pick — approachable, seasonal and endlessly warm.', 0, true, null, true, 'New American', '$$', 'Resy'),
  ('Mirra', 'mirra', 'Bucktown', '1954 W Armitage Ave, Chicago, IL 60622', 'https://www.mirrachicago.com', null, 'New for 2025, this genre-bending Bucktown Bib fuses Indian and Mexican flavors with a chef''s-counter tasting — one of the year''s most exciting arrivals.', 0, true, null, false, 'Indian-Mexican', '$$', 'OpenTable'),
  ('Mi Tocaya Antojeria', 'mi-tocaya-antojeria', 'Logan Square', '2800 W Logan Blvd, Chicago, IL 60647', 'https://www.mitocaya.com', 'https://resy.com/cities/chicago-il/venues/mi-tocaya-antojeria', 'Diana Davila''s heritage-fueled antojeria — peanut-butter lengua, beer-can chicken tacos — is both a Bib Gourmand and an NYT pick, and always a joyful table.', 0, true, null, true, 'Mexican', '$$', 'Resy'),
  ('Mott St.', 'mott-st', 'West Town', '1401 N Ashland Ave, Chicago, IL 60622', 'https://www.mottstreetchicago.com', 'https://www.opentable.com/mott-street', 'A convivial, dimly-lit corner spot plating crave-worthy Asian-American shareables around a signature burger — a fun, easygoing Bib Gourmand date.', 0, true, null, false, 'Asian-American', '$$', 'OpenTable'),
  ('Munno Pizzeria & Bistro', 'munno-pizzeria-and-bistro', 'Ravenswood', '4656 N Clark St, Chicago, IL 60640', 'https://www.munnochicago.com', null, 'A cozy North Side bistro turning out blistered pizzas and homey Italian plates — a neighborhood charmer that quietly earned its Bib.', 0, true, null, false, 'Italian & pizza', '$$', 'OpenTable'),
  ('Nadu', 'nadu', 'Lincoln Park', '2518 N Lincoln Ave, Chicago, IL 60614', 'https://www.naduchicago.com', 'https://resy.com/cities/chicago-il/venues/nadu', 'New for 2025, Sujan Sarkar''s coastal-India Bib weaves Keralan seabass and Punjabi kofta with craft cocktails into a vibrant Lincoln Park date.', 0, true, null, false, 'Regional Indian', '$$', 'Resy'),
  ('Perilla', 'perilla', 'West Loop', '401 N Milwaukee Ave, Chicago, IL 60654', 'https://www.perillachicago.com', null, 'Tableside grilling and communal, tradition-rooted Korean flavors make this West Loop Bib an interactive, hands-on kind of date night.', 0, true, null, false, 'Korean BBQ', '$$', 'OpenTable'),
  ('Pleasant House Pub', 'pleasant-house-pub', 'Pilsen', '2119 S Halsted St, Chicago, IL 60608', 'https://www.pleasanthouse.com', null, 'Flaky royal pies, house ales and a snug Pilsen pub room make this sustainability-minded Bib Gourmand a comforting, unpretentious date.', 0, true, null, false, 'British savory pies', '$', 'Walk-in'),
  ('Proxi', 'proxi', 'West Loop', '565 W Randolph St, Chicago, IL 60661', 'https://www.proxichicago.com', null, 'A soaring, wood-fired West Loop room roaming the globe for smoky street-food flavors — a lively, shareable Bib Gourmand for date night.', 0, true, null, false, 'Global street food', '$$', 'OpenTable'),
  ('Sifr', 'sifr', 'River North', '660 N Orleans St, Chicago, IL 60654', 'https://www.sifrchicago.com', null, 'Colorful, hearth-cooked Middle Eastern mezze and a stunning 97-seat rooftop make this Bib a warm-weather date-night standout in River North.', 0, true, null, false, 'Middle Eastern', '$$', 'Resy'),
  ('Sochi Saigonese Kitchen', 'sochi-saigonese-kitchen', 'Lakeview', '1358 W Belmont Ave, Chicago, IL 60657', 'https://www.sochikitchen.com', null, 'A bright, family-run Lakeview room serving vivid Saigon-style Vietnamese cooking — a friendly, flavorful Bib Gourmand pick.', 0, true, null, false, 'Vietnamese', '$$', 'OpenTable'),
  ('Sol de Mexico', 'sol-de-mexico', 'Belmont Cragin', '3018 N Cicero Ave, Chicago, IL 60641', 'https://soldemexicochicago.com', null, 'A festive Northwest Side destination for complex, mole-driven regional Mexican cooking — a longstanding, worth-the-drive Bib Gourmand.', 0, true, null, false, 'Mexican', '$$', 'Walk-in'),
  ('Superkhana International', 'superkhana-international', 'Logan Square', '3059 W Diversey Ave, Chicago, IL 60647', 'https://www.superkhana.com', 'https://resy.com/cities/chicago-il/venues/superkhana-international', 'The irreverent Indian spot of your dreams, home of the famous butter-chicken calzone — top-notch vibes and food make it a joyous Bib date.', 0, true, null, false, 'Indian', '$$', 'Resy'),
  ('Table, Donkey and Stick', 'table-donkey-and-stick', 'Logan Square', '2728 W Armitage Ave, Chicago, IL 60647', 'https://www.tabledonkeystick.com', 'https://resy.com/cities/chicago-il/venues/table-donkey-and-stick', 'Alpine-inspired cooking, house charcuterie, square latkes and a fab patio give this Palmer Square Bib the feel of a beloved local treasure.', 0, true, null, false, 'Alpine European', '$$', 'Resy'),
  ('Taqueria Chingon', 'taqueria-chingon', 'Bucktown', '2234 N Western Ave, Chicago, IL 60647', null, null, 'New for 2025, this Bucktown taqueria''s blue-corn masa and vibrant tacos earned a Bib Gourmand — a casual, crave-worthy bite before drinks.', 0, true, null, false, 'Mexican (tacos)', '$', 'Walk-in'),
  ('Union', 'union', 'Logan Square', '2202 N California Ave, Chicago, IL 60647', 'https://www.unionlogansquare.com', 'https://resy.com/cities/chicago-il/venues/union', 'Pub grub with pedigree and a deep bourbon-and-beer list, this Logan Square Bib is an easygoing, whiskey-forward neighborhood date.', 0, true, null, false, 'New American', '$', 'Resy'),
  ('Virtue', 'virtue', 'Hyde Park', '1462 E 53rd St, Chicago, IL 60615', 'https://www.virtuerestaurant.com', null, 'Erick Williams''s James Beard-winning Hyde Park dining room serves gracious, soulful Southern cooking — both a Bib Gourmand and a South Side date-night anchor.', 0, true, null, false, 'Southern American', '$$', 'OpenTable'),
  ('Akahoshi Ramen', 'akahoshi-ramen', 'Logan Square', '2340 N California Ave Suite B, Chicago, IL 60647', 'https://www.akahoshiramen.com', null, 'Mike Satinover''s Reddit-famous house-made noodles and deep, glossy broths made this tiny Logan Square shop an NYT-anointed ramen destination.', 0, false, null, true, 'Japanese ramen', '$$', 'Walk-in'),
  ('Asador Bastian', 'asador-bastian', 'River North', '214 W Erie St, Chicago, IL 60654', 'https://asadorbastian.com', null, 'An intimate Basque chophouse in a 120-year-old townhouse, its wood-fired steaks and tapas earning both Esquire and NYT raves — a memorable splurge for two.', 0, false, null, true, 'Basque steakhouse', '$$$$', 'Resy'),
  ('Avec', 'avec', 'West Loop', '615 W Randolph St, Chicago, IL 60661', 'https://www.avecrestaurant.com', null, 'The communal-table original of Randolph Row, its bacon-wrapped dates and focaccia now an NYT pick — cozy, convivial and enduringly great.', 0, false, null, true, 'Mediterranean small plates', '$$', 'Resy'),
  ('Brindille', 'brindille', 'River North', '534 N Clark St, Chicago, IL 60654', 'https://www.brindille-chicago.com', null, 'An elegant Art Deco ode to Parisian fine dining, its caviar and Bordelaise-sauced rib-eye making it an NYT-listed classic for a dressed-up date.', 0, false, null, true, 'French', '$$$$', 'OpenTable'),
  ('Hopleaf', 'hopleaf', 'Andersonville', '5148 N Clark St, Chicago, IL 60640', 'https://www.hopleafbar.com', null, 'A 30-year Andersonville beer temple famous for mussels, frites and its CB&J sandwich — an NYT pick and the definition of a comfortable date.', 0, false, null, true, 'Belgian gastropub', '$$', 'Walk-in'),
  ('Maxwells Trading', 'maxwells-trading', 'Fulton Market', '345 N Morgan St, Chicago, IL 60607', 'https://www.maxwellstrading.com', null, 'Erling Wu-Bower''s warm, wood-fired Fulton Market room roams from pasta to whole fish — a buzzy NYT-listed newcomer built for lingering.', 0, false, null, true, 'New American', '$$$', 'Resy'),
  ('Monteverde', 'monteverde', 'West Loop', '1020 W Madison St, Chicago, IL 60607', 'https://www.monteverdechicago.com', null, 'Sarah Grueneberg''s exuberant pasta laboratory has become a modern Chicago classic — an NYT-listed West Loop table where the tortelli steal the night.', 0, false, null, true, 'Italian (pasta)', '$$$', 'Resy'),
  ('Shanghai Terrace', 'shanghai-terrace', 'Streeterville', '108 E Superior St, Chicago, IL 60611', 'https://www.peninsula.com/en/chicago/hotel-fine-dining/shanghai-terrace-chinese', null, 'A jewel-box, red-lacquered dining room inside The Peninsula with a magical terrace — refined Cantonese cooking and an NYT nod make it a glamorous date.', 0, false, null, true, 'Chinese (Cantonese)', '$$$$', 'OpenTable'),
  ('Superdawg Drive-In', 'superdawg-drive-in', 'Norwood Park', '6363 N Milwaukee Ave, Chicago, IL 60646', 'https://www.superdawg.com', null, 'A gloriously retro 1948 drive-in with carhops and dancing hot-dog mascots — an NYT-listed slice of Chicago nostalgia for a playful, unfussy date.', 0, false, null, true, 'Hot dogs (drive-in)', '$', 'Walk-in'),
  ('Thattu', 'thattu', 'Avondale', '2601 W Fletcher St, Chicago, IL 60618', 'https://thattu.com', null, 'Margaret Pak''s love letter to Kerala''s spice-garden cooking, tucked in an Avondale food hall — an NYT pick bursting with coconut, curry leaf and heat.', 0, false, null, true, 'Keralan Indian', '$$', 'OpenTable'),
  ('The Duck Inn', 'the-duck-inn', 'Bridgeport', '2701 S Eleanor St, Chicago, IL 60608', 'https://www.theduckinnchicago.com', null, 'A handsome Bridgeport gastro-tavern famed for its rotisserie duck and retro cocktails — an NYT-listed neighborhood gem that feels like a secret.', 0, false, null, true, 'New American', '$$$', 'Resy'),
  ('The Loyalist', 'the-loyalist', 'West Loop', '177 N Ada St, Chicago, IL 60607', 'https://www.smythandtheloyalist.com', null, 'The moody downstairs sibling to three-star Smyth, home to the cult ''dirty burger'' — an NYT pick that delivers fine-dining pedigree in a relaxed booth.', 0, false, null, true, 'New American gastropub', '$$$', 'Resy'),
  ('Uncle John''s Bar-B-Que', 'uncle-johns-bar-b-que', 'Greater Grand Crossing', '337 E 69th St, Chicago, IL 60637', null, null, 'A South Side aquarium-smoker institution turning out rib tips and hot links with tangy sauce — an NYT-honored, no-frills BBQ pilgrimage.', 0, false, null, true, 'Barbecue', '$', 'Walk-in'),
  ('Warlord', 'warlord', 'Avondale', '3198 N Elston Ave, Chicago, IL 60618', 'https://www.warlordchicago.com', null, 'A dark, hearth-driven Avondale hotspot cooking whatever the fire dictates that day — an Esquire and NYT darling for adventurous, in-the-know couples.', 0, false, null, true, 'Live-fire American', '$$$', 'Resy'),
  ('Kumiko', 'kumiko', 'West Loop', '630 W Lake St, Chicago, IL 60661', 'https://barkumiko.com', 'https://resy.com/cities/chicago-il/venues/kumiko', 'Julia Momose''s Japanese dining bar treats cocktails as ceremony — ranked North America''s #11, crowned World''s Best Bar at the 2025 Spirited Awards, and the city''s most transporting drinks date.', 0, false, 'North America''s 50 Best Bars #11', false, 'Japanese cocktail & dining bar', '$$$', 'Resy'),
  ('Best Intentions', 'best-intentions', 'Logan Square', '3281 W Armitage Ave, Chicago, IL 60647', 'https://www.bestintentionschicago.com', null, 'A Midwestern-kitsch corner tap where world-class drinks meet dive-bar ease — Angostura on tap, a grasshopper malted, and a No. 16 spot in North America''s best.', 0, false, 'North America''s 50 Best Bars #16', false, 'Cocktail bar', '$', 'Walk-in'),
  ('Gus'' Sip & Dip', 'gus-sip-and-dip', 'River North', '51 W Hubbard St, Chicago, IL 60654', 'https://gussipanddip.com', null, 'A playful, nostalgia-soaked River North newcomer whose serious drinks vaulted it to No. 27 in North America — walk-in only and worth the wait.', 0, false, 'North America''s 50 Best Bars #27', false, 'Cocktail bar', '$$$', 'Walk-in'),
  ('Bisous', 'bisous', 'Fulton Market', '938 W Fulton Market, Chicago, IL 60607', 'https://www.bisouschicago.com', null, 'A ''60s-Parisian fantasy and the lone standalone cocktail bar on Restaurant Row, its design-forward glamour earning a No. 30 North America ranking — pure date-night romance.', 0, false, 'North America''s 50 Best Bars #30', false, 'French cocktail bar', '$$$', 'Walk-in'),
  ('Meadowlark', 'meadowlark', 'Logan Square', '2812 W Palmer St, Chicago, IL 60647', 'https://www.meadowlarkchicago.com', 'https://resy.com/cities/chicago-il/venues/the-meadowlark', 'A cozy, soulful Logan Square cocktail den on North America''s extended 51-100 list — intimate enough to make it feel like your own discovery.', 0, false, 'North America''s 50 Best Bars #65 (extended list)', false, 'Cocktail bar', '$$', 'Resy'),
  ('Nine Bar', 'nine-bar', 'Chinatown', '216 W Cermak Rd, Chicago, IL 60616', 'https://www.ninebarchicago.com', null, 'Chinatown''s first speakeasy-style cocktail bar, a moody hideaway on North America''s extended list — a novel, off-the-radar spot for a drinks date.', 0, false, 'North America''s 50 Best Bars #76 (extended list)', false, 'Cocktail bar', '$', 'Walk-in'),
  ('Queen Mary Tavern', 'queen-mary-tavern', 'Wicker Park', '2125 W Division St, Chicago, IL 60622', 'https://www.queenmarytavern.com', null, 'A nautical-themed Wicker Park tavern with serious cocktails and a rollicking vibe, sailing onto North America''s extended list at No. 80.', 0, false, 'North America''s 50 Best Bars #80 (extended list)', false, 'Cocktail bar', '$$', 'Walk-in');

-- 1) insert brand-new venues (skip anything already on the site, by name)
insert into places (name, slug, neighborhood, address, website_url, reservation_url, description, status, is_date_night)
select s.name, s.slug, s.neighborhood, s.address, s.website_url, s.reservation_url, s.description, 'approved', true
from dn_seed s
where not exists (select 1 from places p where lower(p.name) = lower(s.name))
on conflict (slug) do nothing;

-- 2) flag existing venues that are also date-night spots
update places p set is_date_night = true
from dn_seed s where lower(p.name) = lower(s.name);

-- 3) attach the date_nights accolade row to each place (by name)
insert into date_nights (place_id, michelin_stars, bib_gourmand, fifty_best, nyt, cuisine, price, reservation_platform, vibe, verified_at)
select p.id, s.michelin_stars, s.bib_gourmand, s.fifty_best, s.nyt, s.cuisine, s.price, s.reservation_platform, s.description, now()
from places p
join dn_seed s on lower(p.name) = lower(s.name)
on conflict (place_id) do nothing;
