// Cheeky-but-classy one-liners shown on the splash screen. One is picked at
// random on every visit to the homepage.
export const HAPPY_HOUR_QUIPS = [
  "Leave work early. We'll cover for you.",
  "It's 5 o'clock somewhere. Here, it's now.",
  "The ice is chilling. So should you.",
  "Cocktails don't pour themselves. Someone has to show up.",
  "Your spreadsheet can wait. Your martini can't.",
  "Chicago's happy hours, hand-picked by people who take this seriously.",
  "We found the deals. You bring the thirst.",
  "Half-price oysters wait for no one.",
  "Somewhere in this city, a bartender is waiting for you.",
  "The Loop can wait. The bar can't.",
  "Punch out. Pour in.",
  "This is not a drill. It's happy hour.",
  "Good taste, better timing.",
  "River North doesn't sleep, but it does discount.",
  "You've earned this. Probably.",
  "Martinis are just olives with commitment issues.",
  "West Loop wine, Gold Coast oysters, your choice.",
  "The early bird gets the $5 beer.",
  "Old Town's oldest trick: cheap drinks, good company.",
  "Skip the line. Skip the markup.",
  "A round of applause for whoever invented happy hour.",
  "Lincoln Park has a secret. It's called 4pm.",
  "Nobody ever regretted an early exit for a good deal.",
  "The Loop's rooftop views, discounted.",
  "Cheap doesn't mean cheap when it's this good.",
  "We rate happy hours the way Gabby rates whiskey. Ruthlessly.",
  "Somebody has to drink the discounted wine. Might as well be you.",
  "Fashionably early beats fashionably late tonight.",
  "This app has strong opinions about oysters.",
  "Chicago's best kept secret is that it isn't a secret.",
  "Your 4pm meeting could've been a happy hour.",
  "We did the research so you don't Google 'happy hour near me' again.",
  "A martini a day keeps the Monday away.",
  "The only spreadsheet worth your time is this one.",
  "Deals expire. Regret doesn't.",
  "Somewhere between the office and home, there's a better plan.",
  "Bib Gourmand fried chicken doesn't discount itself.",
  "You could go home. Or you could go to Gilt Bar.",
  "This city has more happy hours than excuses to skip them.",
  "Half off oysters is basically a public service.",
  "We believe in early exits and honest reviews.",
  "The best decisions happen before 6pm.",
  "Somewhere, a bartender just cracked fresh ice for you.",
  "If it's not discounted, is it even happy hour?",
  "Rush Street doesn't discriminate. Neither does happy hour.",
  "There's a $10 cocktail out there with your name on it.",
  "Fulton Market's happy hours hit different.",
  "This city runs on happy hour math: less money, more fun.",
  "The tavern chic era of your Tuesday starts now.",
  "Old fashioneds taste better before 7pm.",
  "Somewhere, a wine glass is half full and half price.",
  "We're not saying skip the gym. We're saying happy hour first.",
  "Consider this your permission slip.",
  "A good happy hour is a love language.",
  "Espresso martinis: the adult version of a coffee break.",
  "Every neighborhood has a happy hour worth bragging about.",
  "The best kind of Chicago winter plan involves indoor oysters.",
  "You don't need a reason. You need a reservation.",
  "This is what 'leave work early' was invented for.",
  "Somewhere in River North, ice is being shaken on purpose.",
  "Happy hour: the most honest two words in hospitality.",
  "Cheers to whoever decided 4pm counts as evening.",
  "We take our happy hours as seriously as Gabby takes her whiskey.",
  "The oysters don't wait around, and neither should you.",
  "A discount this good deserves a toast.",
  "Chicago's bars have secrets. We just publish them.",
  "You had a long day. The bar had a longer happy hour.",
  "Some cities nap at 4pm. Chicago pours.",
  "This is the fine print you actually want to read.",
  "The martini glass is half full. Literally, right now, somewhere.",
  "Good taste doesn't have to cost full price.",
  "Somewhere, a $5 draft is being poured in your honor.",
  "We believe happy hour is a civic duty.",
  "Gold Coast glamour, budget-friendly hours.",
  "Even our buttons wobble. Your plans should too.",
  "This is your sign to leave the desk.",
  "Happy hour doesn't RSVP. Neither should you.",
  "Every great night starts with a great deal.",
  "The oysters are half off. The excuses are fully gone.",
  "Somewhere in this city, someone just said 'one more round' unironically.",
  "The only meeting worth attending starts at the bar.",
  "This city's happy hours have more range than a jazz set at Tortoise.",
  "A discount, a view, and a reason to stay a little longer.",
  "We're pro-happy hour and anti-overpaying.",
  "Somebody pour Gabby a whiskey. She's earned it. So have you.",
  "The classiest thing you'll do all week starts at 4pm.",
  "Happy hour: proof that good things come to those who leave early.",
  "There's a reservation with your name on it. Probably.",
  "The bar is calling. It's a landline. It's very old fashioned.",
  "Every deal on this list has been vetted, sipped, and approved.",
  "This city's happy hours deserve their own holiday.",
  "Somewhere between the Loop and Lincoln Park, happiness is 40% off.",
  "We measure success in oysters half-priced.",
  "Chicago doesn't do subtle happy hours. Neither do we.",
  "The best kind of peer pressure is a group happy hour.",
  "This isn't procrastination. This is strategic timing.",
  "A martini, a view, and zero regrets.",
  "Somewhere, a bartender is polishing a glass just for you.",
  "The tavern chic life chose you. Either way, cheers.",
  "Leave work early. We already told you where.",
];
