// Restaurant logo marks, keyed by exact `places.name`. `dark: true` means the
// logo is light/white and needs a dark chip behind it to read; otherwise it
// sits on the default paper chip.
export const PLACE_LOGOS = {
  Aba: { src: "/logos/aba.png", dark: true },
  Beatrix: { src: "/logos/beatrix.png", dark: true },
  Benchmark: { src: "/logos/benchmark.png", dark: true },
  "Gilt Bar": { src: "/logos/gilt-bar.png", dark: true },
  "Hub 51": { src: "/logos/hub-51.png", dark: true },
  "J9 Wine Bar": { src: "/logos/j9-wine-bar.png", dark: false },
  "Old Town Pour House": { src: "/logos/old-town-pour-house.png", dark: false },
  "RPM Italian": { src: "/logos/rpm-italian.png", dark: false },
  "Shaw's Crab House": { src: "/logos/shaws-crab-house.png", dark: true },
  "The Publican": { src: "/logos/the-publican.png", dark: false },
  "The VIG": { src: "/logos/the-vig.png", dark: true },
  "Tortoise Supper Club": { src: "/logos/tortoise-supper-club.png", dark: false },


  // ---- River North batch (added July 20, 2026) ----
  "Bub City": { src: "/logos/bub-city.png", dark: true },
  "RPM Steak": { src: "/logos/rpm-steak.png", dark: true },
  "RPM Seafood": { src: "/logos/rpm-seafood.png", dark: false },
  "Siena Tavern": { src: "/logos/siena-tavern.png", dark: false },
  "Untitled Supper Club": { src: "/logos/untitled-supper-club.png", dark: true },
  "The Kerryman": { src: "/logos/the-kerryman.png", dark: true },
  Tanta: { src: "/logos/tanta-river-north.png", dark: true },
  "Kinzie Chophouse": { src: "/logos/kinzie-chophouse.png", dark: false },
  Wildfire: { src: "/logos/wildfire-river-north.png", dark: true },
  "Osteria Via Stato": { src: "/logos/osteria-via-stato.png", dark: false },
  "Quartino Ristorante": { src: "/logos/quartino-ristorante.png", dark: false },
  Barrio: { src: "/logos/barrio-river-north.png", dark: false },
  "River Roast": { src: "/logos/river-roast.png", dark: true },
  "Hubbard Inn": { src: "/logos/hubbard-inn.png", dark: false },
  "The Hampton Social": { src: "/logos/the-hampton-social-river-north.png", dark: false },
  "Sunda New Asian": { src: "/logos/sunda-new-asian-river-north.png", dark: false },
  "90th Meridian": { src: "/logos/90th-meridian.png", dark: false },
  "About Last Knife": { src: "/logos/about-last-knife.png", dark: false },
  "Acanto": { src: "/logos/acanto.png", dark: true },
  "AceBounce": { src: "/logos/acebounce.png", dark: true },
  "Adalina": { src: "/logos/adalina.png", dark: false },
  "Avaspi": { src: "/logos/avaspi.png", dark: false },
  "Avli Taverna": { src: "/logos/avli-taverna.png", dark: false },
  "BITES Asian Kitchen + Bar": { src: "/logos/bites-asian-kitchen-bar.jpg", dark: false },
  "Bandit": { src: "/logos/bandit.png", dark: true },
  "Bar Siena": { src: "/logos/bar-siena.png", dark: false },
  "Beatrix Loop": { src: "/logos/beatrix-loop.png", dark: true },
  "Blue Sushi Sake Grill": { src: "/logos/blue-sushi.svg", dark: false },
  "Bodega Taqueria y Tequila": { src: "/logos/bodega-taqueria-west-loop.png", dark: false },
  "Boleo": { src: "/logos/boleo.png", dark: true },
  "Burton Place": { src: "/logos/burton-place.png", dark: true },
  "Butcher's Tap": { src: "/logos/butchers-tap.png", dark: true },
  "Cabra": { src: "/logos/cabra.jpg", dark: false },
  "Café Ba-Ba-Reeba!": { src: "/logos/cafe-ba-ba-reeba.png", dark: true },
  "Cindy's": { src: "/logos/cindys.jpg", dark: false },
  "City Winery West Loop": { src: "/logos/city-winery-west-loop.png", dark: false },
  "Corcoran's Grill & Pub": { src: "/logos/corcorans-grill-pub.png", dark: false },
  "Costera Cocina Tulum": { src: "/logos/costera-cocina-tulum.png", dark: false },
  "Declan's Irish Pub": { src: "/logos/declans-irish-pub.png", dark: false },
  "Drew's on Halsted": { src: "/logos/drews-on-halsted.png", dark: false },
  "Eduardo's Enoteca": { src: "/logos/eduardos-enoteca.jpg", dark: false },
  "El Nuevo Mexicano": { src: "/logos/el-nuevo-mexicano.jpg", dark: false },
  "Elephant & Castle (Adams)": { src: "/logos/elephant-and-castle-adams.png", dark: false },
  "Elephant & Castle (Wabash)": { src: "/logos/elephant-and-castle-wabash.png", dark: false },
  "Federales Fulton Market": { src: "/logos/federales-fulton-market.png", dark: true },
  "Felix": { src: "/logos/felix-lakeview.jpg", dark: false },
  "Figo Wine Bar": { src: "/logos/figo-wine-bar.jpg", dark: false },
  "Finley Dunne's Tavern": { src: "/logos/finley-dunnes-tavern.jpg", dark: false },
  "Flight Club": { src: "/logos/flight-club-chicago.png", dark: false },
  "Formento's": { src: "/logos/formentos.jpg", dark: true },
  "Galit": { src: "/logos/galit.jpg", dark: false },
  "Gaslight Bar & Grille": { src: "/logos/gaslight-bar-and-grille.png", dark: true },
  "Grapes & Grains": { src: "/logos/grapes-and-grains.png", dark: true },
  "Gus' Sip & Dip": { src: "/logos/gus-sip-and-dip.png", dark: true },
  "Happy Camper Old Town": { src: "/logos/happy-camper-old-town.png", dark: true },
  "Homeslice": { src: "/logos/homeslice.png", dark: false },
  "Hugo's Frog Bar": { src: "/logos/hugos-frog-bar.svg", dark: false },
  "Kamehachi": { src: "/logos/kamehachi-old-town.svg", dark: false },
  "Kayao": { src: "/logos/kayao.png", dark: false },
  "La Josie": { src: "/logos/la-josie.jpg", dark: true },
  "La Storia": { src: "/logos/la-storia.png", dark: false },
  "Land & Lake Kitchen": { src: "/logos/land-and-lake-kitchen.jpg", dark: false },
  "Le Petit Marcel": { src: "/logos/le-petit-marcel.png", dark: false },
  "Maple & Ash": { src: "/logos/maple-and-ash.png", dark: false },
  "Mia Francesca": { src: "/logos/mia-francesca-lakeview.png", dark: true },
  "Mon Ami Gabi": { src: "/logos/mon-ami-gabi.png", dark: false },
  "Parlor Pizza Bar (West Loop)": { src: "/logos/parlor-pizza-bar-west-loop.png", dark: false },
  "Petterino's": { src: "/logos/petterinos.jpg", dark: false },
  "ROOF on theWit": { src: "/logos/roof-on-thewit.jpg", dark: false },
  "Ramen-san (Fulton Market)": { src: "/logos/ramen-san-fulton-market.png", dark: true },
  "Ramen-san Lincoln Park": { src: "/logos/ramen-san-lincoln-park.png", dark: true },
  "Remington's": { src: "/logos/remingtons.png", dark: true },
  "Sheffield's Beer Garden": { src: "/logos/sheffields-beer-garden.jpg", dark: false },
  "Sparrow": { src: "/logos/sparrow.jpg", dark: false },
  "Summer House Santa Monica": { src: "/logos/summer-house-santa-monica.png", dark: false },
  "Sushi-san Lincoln Park": { src: "/logos/sushi-san-lincoln-park.png", dark: true },
  "Sushi-san Willis Tower": { src: "/logos/sushi-san-willis-tower.png", dark: true },
  "Swift & Sons": { src: "/logos/swift-and-sons.png", dark: true },
  "Swift Tavern": { src: "/logos/swift-tavern-wrigleyville.png", dark: true },
  "Tavern on Rush": { src: "/logos/tavern-on-rush.jpg", dark: false },
  "The Dearborn": { src: "/logos/the-dearborn.png", dark: false },
  "The Fireplace Inn": { src: "/logos/the-fireplace-inn.png", dark: false },
  "The Gage": { src: "/logos/the-gage.jpg", dark: true },
  "The Grillroom": { src: "/logos/the-grillroom-chophouse.png", dark: false },
  "The J. Parker": { src: "/logos/the-j-parker.png", dark: true },
  "The Loyalist": { src: "/logos/the-loyalist.png", dark: false },
  "The Rabbit Hole": { src: "/logos/the-rabbit-hole.png", dark: false },
  "The Roanoke": { src: "/logos/the-roanoke.svg", dark: false },
  "The Tin Lizzie": { src: "/logos/the-tin-lizzie.png", dark: true },
  "The Village": { src: "/logos/the-village-italian-village.png", dark: false },
  "Venteux": { src: "/logos/venteux.png", dark: false },
  "Woodie's Flat": { src: "/logos/woodies-flat.png", dark: false },
};

export function getPlaceLogo(name) {
  return PLACE_LOGOS[name] || null;
}
